services:
  # Banco de Dados com POSTGRES
  db:
    image: postgres:16-alpine
    container_name: gestao
    environment:
      - POSTGRES_DB=gestao
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    networks:
      - internal_net
    ports:
      - "5432:5432"
    volumes:
      - gestao_data:/var/lib/postgresql/data


networks:
  internal_net:
    driver: bridge

volumes:
  gestao_data:
